import { z } from "zod";

// ─── Curriculum Build Request ────────────────────────────────────────────────

/**
 * A request to generate a full curriculum for a skill.
 * The builder will produce one or more topics, each mapped to a LessonSpec
 * generated by the StagedContentCompiler pipeline.
 */
export const CurriculumBuildRequestSchema = z.object({
    /** The target skill this curriculum belongs to. */
    skillId: z.string(),

    /** High-level subject domain (e.g., "Rust Programming", "Machine Learning Fundamentals"). */
    domain: z.string(),

    /** Freeform description of the learner audience and desired depth. */
    audienceDescription: z.string().optional(),

    /**
     * Optional list of topic strings to seed the curriculum.
     * If omitted, the builder derives topics from the domain automatically.
     */
    seedTopics: z.array(z.string()).optional(),

    /**
     * Maximum number of lessons/topics to generate.
     * @default 5
     */
    maxTopics: z.number().int().min(1).max(20).default(5),

    /** Provenance metadata for the build. */
    provenance: z.object({
        requestedBy: z.string(),
        requestedAt: z.string(), // ISO datetime
    }).optional(),
});

export type CurriculumBuildRequest = z.infer<typeof CurriculumBuildRequestSchema>;

// ─── Capability Map Entry ─────────────────────────────────────────────────────

/**
 * A single entry in the capability map — maps a topic to a specific ability
 * and the compiler run that generated it.
 */
export const CapabilityMapEntrySchema = z.object({
    /** The topic name (e.g., "Rust Lifetimes"). */
    topic: z.string(),

    /**
     * The stable lesson ID derived from this topic.
     * Conventionally: `lesson-{slugified-topic}`.
     */
    lessonId: z.string(),

    /**
     * The compiler run ID used to generate this lesson.
     * Can be used to trace back to the full CompilerRun artifact.
     */
    compilerRunId: z.string(),

    /**
     * The ordering index of this topic within the generated curriculum.
     * Lower = earlier in the learning sequence.
     */
    sequenceIndex: z.number().int().min(0),

    /** Whether this lesson has been packaged as a LessonVersion (published). */
    published: z.boolean().default(false),
});

export type CapabilityMapEntry = z.infer<typeof CapabilityMapEntrySchema>;

// ─── Curriculum Builder Interface ─────────────────────────────────────────────

/**
 * CurriculumBuilder orchestrates the StagedContentCompiler to generate a
 * sequence of lessons for a full skill curriculum.
 *
 * Implementation will use StagedContentCompiler (from D1) as the engine.
 * This stub defines the interface and the async generator API.
 */
export interface CurriculumBuilder {
    /**
     * Build a curriculum from a request.
     *
     * Yields a `CapabilityMapEntry` for each topic as it is generated,
     * allowing callers to observe progress incrementally.
     *
     * @yields {CapabilityMapEntry} One entry per generated topic/lesson.
     */
    build(request: CurriculumBuildRequest): AsyncGenerator<CapabilityMapEntry, void, unknown>;
}
